### ISSUE TITLE
getInnterText throws

### ISSUE THREAD

**Issue by AdmiralSnyder** [Guyiming/Highlight.Blazor#1]
hey, you create a function `getInnterText` ... which (in my env) throws. - i don't think that's on purpose. it does repro with 0.0.18 and 0.0.19.

pls ping me if you want more details :-)

**Comment by Guyiming** [comment]
Hi @AdmiralSnyder ,`getInnterText` defined in `highlight-blazor.js`.  Can you check the file if it loads correctly?
