### ISSUE TITLE
Object of type 'HighlightBlazor.CodeHighlight' does not have a property matching the name 'style'.

### ISSUE THREAD

**Issue by olga-athana** [Guyiming/Highlight.Blazor#5]
I tried to set the style of the CodeHighlight element and it exists in the context menu when I'm typing in Visual Studio but when I run the application I get the error:
"Message: Object of type 'HighlightBlazor.CodeHighlight' does not have a property matching the name 'style'.
Source: Microsoft.AspNetCore.Components
Inner exception:"

**Comment by Guyiming** [comment]
`CodeHighlight` doen't support `style`，if you want set the style of the code, try use the `HighlightService`.

**Comment by olga-athana** [comment]
Good to know. Thanks!
